app:
  scheduler:
    enable: true
    interval: 10000
    force-check-delay: 10000
    time-for-check: 1
  database-access-type: jdbc
  kafka:
    bootstrap-servers: ${DOCKER_HOST_IP:127.0.0.1}:9092
    topic-name: bot-updates
    linger-ms: 10
    trusted-packages: "*"
  use-queue: true

spring:
  application:
    name: scrapper
  datasource:
    url: jdbc:postgresql://localhost:5432/scrapper
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  liquibase:
    enabled: false

server:
  port: 8080

management:
  server:
    port: 8081

  endpoints:
    web:
      base-path: /
      exposure:
        include: info, health, prometheus
      path-mapping:
        prometheus: /metrics
    enabled-by-default: true

  metrics:
    tags:
      application: ${spring.application.name}

logging:
  config: classpath:log4j2-plain.xml

api:
  github:
    base-url: https://api.github.com
    retry-policy: exponential
    attempts: 5
    statuses: INTERNAL_SERVER_ERROR, SERVICE_UNAVAILABLE, BAD_GATEWAY
  stackoverflow:
    base-url: https://api.stackexchange.com/2.3
    retry-policy: exponential
    attempts: 5
    statuses: INTERNAL_SERVER_ERROR, SERVICE_UNAVAILABLE, BAD_GATEWAY
  bot:
    base-url: http://localhost:8090
    retry-policy: exponential
    attempts: 5
    statuses: INTERNAL_SERVER_ERROR, SERVICE_UNAVAILABLE, BAD_GATEWAY

bucket:
  tokens: 50
  refill-tokens: 10

springdoc:
  swagger-ui:
    path: /swagger-ui

