app:
  telegram-token: ${TELEGRAM_API_KEY}

spring:
  application:
    name: bot
  jackson:
    time-zone: UTC

server:
  port: 8090

logging:
  config: classpath:log4j2-plain.xml

api:
  scrapper:
    base-url: http://localhost:8080
    retry-policy: exponential
    attempts: 5
    statuses: INTERNAL_SERVER_ERROR, SERVICE_UNAVAILABLE, BAD_GATEWAY

bucket:
  tokens: 50
  refill-tokens: 10

springdoc:
  swagger-ui:
    path: /swagger-ui
