app:
  telegram-token: ${TELEGRAM_API_KEY}
  kafka:
    bootstrap-servers: ${DOCKER_HOST_IP:127.0.0.1}:9092
    topic-name: bot-updates
    bad-topic-name: bot-updates_dlq
    group-id: bot
    type-mappings: edu.java.api.components.LinkUpdateRequest:edu.java.bot.api.components.LinkUpdateRequest
    trusted-packages: "*"
  micrometer:
    name: updates_counter
    description: count of updates processed

spring:
  application:
    name: bot
  jackson:
    time-zone: UTC

server:
  port: 8090

management:
  server:
    port: 8091

  endpoints:
    web:
      base-path: /
      exposure:
        include: info, health, prometheus
      path-mapping:
        prometheus: /metrics
    enabled-by-default: true

  metrics:
    tags:
      application: ${spring.application.name}

logging:
  config: classpath:log4j2-plain.xml

api:
  scrapper:
    base-url: http://localhost:8080
    retry-policy: exponential
    attempts: 5
    statuses: INTERNAL_SERVER_ERROR, SERVICE_UNAVAILABLE, BAD_GATEWAY

bucket:
  tokens: 50
  refill-tokens: 10

springdoc:
  swagger-ui:
    path: /swagger-ui
